# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARTest
  pod 'ARCore/AugmentedFaces', '~> 1.23.0'  

end
